# Server Configuration
server.port=5000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://ajay:12345@cluster0.rozdp0g.mongodb.net/civicpulse?appName=Cluster0

# Application JWT Secret Key
jwt.secret=1e58d2781a184c929d06397d8504325d1e58d2781a184c929d06397d8504325d

# Logging Level
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.civicpulse.backend=DEBUG
